
const originalList = [
    "course",
    "session-cancelled",
    "start-time",
    "end-time",
    "duration",
    "cost",
    "term",
    "class-type",
    "instructor",
    "delivery-method",
    "room",
    "session-capacity",
    "remaining-capacity",
    "zoom-link",
    "activity-fee",
    "where",
    "available-online",
    "name",
    "name",
    "course",
    "group-type",
    "contact",
    "organisation",
    "purpose-of-hire",
    "estimated-number-of-people",
    "number-of-people-who-live-in-municipality",
    "public-liability-insurance",
    "insurance-policy",
    "surcharge-added-to-fees",
    "group-incorporated",
    "contact-details-of-security-company",
    "will-alcohol-be-served",
    "will-alcohol-be-sold",
    "liquor-license",
    "application-form",
]

const uniqueList = [...new Set(originalList)];
console.log(uniqueList);
